server:
  port: 9000

spring:
  application:
    name: eagle-center
  security:
    user:
      name: admin
      password: 123456

eureka:
  instance:
    hostname: localhost
    appname: eagle-center
    lease-renewal-interval-in-seconds: 5    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15    # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
  #    instance-id: 127.0.0.1:9000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
#    healthcheck:
#      enabled: true    # 开启健康检查（依赖spring-boot-starter-actuator）
#  server:
#    enable-self-preservation: false    # 设为false，关闭自我保护
#    eviction-interval-timer-in-ms: 5000    # 清理间隔（单位毫秒，默认是60*1000）
