server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:9000/eureka/
  instance:
    hostname: localhost
    appname: eagle-api
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
#    instance-id: 127.0.0.1:9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    druid:
      url: jdbc:mysql://主机ip:端口/eagle?characterEncoding=UTF-8&useSSL=false
      username: your database username
      password: your database password
      driver-class-name: com.mysql.jdbc.Driver
      #初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 100000
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat, wall, logback
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  profiles:
    active: @profileActive@
  application:
    name: eagle-api
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:9008
# mybatis-plus配置
mybatis-plus:
  # xml位置
  mapper-locations: classpath:/com/soaring/eagle/api/module/**/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.soaring.eagle.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置 SQL注入器。 这里为了处理逻辑删除操作，使用了LogicSqlInjector注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    call-setters-on-nulls: true
    cache-enabled: false
    # 数据库字段与数据对象字段的映射策略
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null

# 不能CxfConfig中配置，否则项目启动不了
cxf:
  path: /eagle/webservice
